In [ ]:
# importing Pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
# Creating tensors in PyTorch

In [5]:
scalar = torch.tensor(7)
scalar                   #created using torch.tensor

tensor(7)

In [6]:
scalar.item() #get as python int

7

In [ ]:
# vectors

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim #ndim = number of dimensions

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix - has 2 dimensions

In [14]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [3,4,5],
                      [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [20]:
TENSOR.shape #here 1 is 0->1, 3 is rows of 3, 3 is columns of 3

torch.Size([1, 3, 3])

In [ ]:
# scalar, vector uses lower cases letters where as matrix and tensors uses upper case letters

In [21]:
# Random Tensors

neural networks learn in a way as they always start with random numbers and update them to better represent the data.